Define local variables instead of passing anonymous structs to mempcpy()
gcc 5 fails to compile the current code with an error like this:

src/caencoder.c: In function ‘ca_encoder_get_entry_data’:
src/caencoder.c:984:51: error: macro "mempcpy" passed 5 arguments, but takes
just 3
                             sizeof(CaFormatHeader));
                                                   ^
src/caencoder.c:979:19: warning: assignment from incompatible pointer type
[-Wincompatible-pointer-types]
                 p = mempcpy(p,
                   ^
src/caencoder.c:994:51: error: macro "mempcpy" passed 5 arguments, but takes
just 3
                             sizeof(CaFormatHeader));
                                                   ^
src/caencoder.c:989:19: warning: assignment from incompatible pointer type
[-Wincompatible-pointer-types]
                 p = mempcpy(p,
                   ^
src/caencoder.c:1013:46: error: macro "mempcpy" passed 5 arguments, but
takes just 3
                        sizeof(CaFormatHeader));
                                              ^
src/caencoder.c:1008:19: warning: assignment from incompatible pointer type
[-Wincompatible-pointer-types]
                 p = mempcpy(p,
                   ^